import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { renderSourceDependencies } from "../src/source-deps.ts";
import {
  missingRustComponents,
  verifyEnvironmentFingerprint,
} from "../src/environment-verification.ts";

function repository(packageManager = `bun@${Bun.version}`): string {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-environment-verify-"));
  writeFileSync(
    join(root, "package.json"),
    `${JSON.stringify({ name: "fixture", packageManager }, null, 2)}\n`,
  );
  writeFileSync(
    join(root, ".repository-environment.toml"),
    `schema_version = 1

[policy]
track = "latest-stable"

[system]
apt = []

[compatibility_holds]
`,
  );
  mkdirSync(join(root, "scripts"), { recursive: true });
  writeFileSync(
    join(root, "scripts", "codex-environment.sh"),
    '#!/usr/bin/env bash\nmode="${1:-setup}"\n[[ "$mode" == "setup" || "$mode" == "maintenance" ]]\n',
  );
  return root;
}

describe("environment verification receipt", () => {
  test("certifies a matching observed environment with the expected fingerprint", () => {
    const root = repository();

    const result = verifyEnvironmentFingerprint(root);

    expect(result.status).toBe("passed");
    expect(typeof result.data.expectedFingerprint).toBe("string");
    expect(result.data.verifiedFingerprint).toBe(result.data.expectedFingerprint);
    expect(result.diagnostics).toEqual([]);
  });

  test("does not certify an exact but mismatched toolchain", () => {
    const root = repository("bun@0.0.1");

    const result = verifyEnvironmentFingerprint(root);

    expect(result.status).toBe("failed");
    expect(result.data.verifiedFingerprint).toBeNull();
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({ code: "environment-toolchain-mismatch", path: "package.json" }),
    );
  });

  test("matches declared Rust component names against target-qualified rustup output", () => {
    const listing = [
      "cargo-x86_64-unknown-linux-gnu (installed)",
      "clippy-x86_64-unknown-linux-gnu (installed)",
      "rustfmt-x86_64-unknown-linux-gnu (installed)",
    ].join("\n");

    expect(missingRustComponents(["clippy", "rustfmt"], listing)).toEqual([]);
    expect(missingRustComponents(["clippy", "rust-src", "rustfmt"], listing)).toEqual([
      "rust-src",
    ]);
  });

  test("keeps managed source mode out of the default environment identity", () => {
    const root = repository();
    mkdirSync(join(root, ".cargo"), { recursive: true });
    writeFileSync(
      join(root, ".cargo", "config.toml"),
      "# Generated by coding-tooling source-deps. Do not edit.\n\n[patch.crates-io]\n",
    );

    const result = verifyEnvironmentFingerprint(root);

    expect(result.status).toBe("failed");
    expect(result.data.verifiedFingerprint).toBeNull();
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({ code: "environment-source-profile-mismatch" }),
    );
  });

  test("certifies an explicitly active exact source-development profile", () => {
    const root = repository();
    writeFileSync(
      join(root, ".coding-tooling.source-deps.json"),
      `${JSON.stringify(
        {
          schemaVersion: 2,
          cargo: {
            localOnly: false,
            patches: [
              {
                package: "foundation-a",
                git: "https://example.invalid/foundation",
                rev: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              },
            ],
          },
        },
        null,
        2,
      )}\n`,
    );
    const rendered = renderSourceDependencies(root);
    mkdirSync(join(root, ".cargo"), { recursive: true });
    writeFileSync(rendered.cargoConfigPath, rendered.content);

    const result = verifyEnvironmentFingerprint(root, "source-development");

    expect(result.status).toBe("passed");
    expect(result.data.verifiedFingerprint).toBe(result.data.expectedFingerprint);
    expect(result.diagnostics).toEqual([]);
  });
});
