import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { runConventionChecks } from "../src/convention-enforcement.ts";
import { discoverComponents } from "../src/core.ts";

function enforce(root: string, ruleId: string, check: string): void {
  const directory = join(root, ".conventions", "modules", "fixture");
  mkdirSync(directory, { recursive: true });
  writeFileSync(
    join(directory, `${ruleId}.json`),
    `${JSON.stringify(
      {
        schemaVersion: 1,
        ruleId,
        enforcement: { kind: "builtin", check },
      },
      null,
      2,
    )}\n`,
  );
}

function reactRepository(): string {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-react-order-"));
  mkdirSync(join(root, "src"));
  writeFileSync(
    join(root, "package.json"),
    `${JSON.stringify(
      {
        name: "react-fixture",
        dependencies: { react: "1" },
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(join(root, "tsconfig.json"), "{}\n");
  return root;
}

function dotnetRepository(): string {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-csharp-order-"));
  writeFileSync(join(root, "Fixture.csproj"), '<Project Sdk="Microsoft.NET.Sdk"></Project>\n');
  return root;
}

describe("deterministic source ordering", () => {
  test("keeps named React props immediately above the component that consumes them", () => {
    const root = reactRepository();
    const source = join(root, "src", "Card.tsx");
    enforce(root, "REACT-005", "react-props-adjacency");

    writeFileSync(
      source,
      `type CardProps = { title: string };\nexport function Card(props: CardProps) { return <div>{props.title}</div>; }\n`,
    );
    expect(runConventionChecks(root, discoverComponents(root)).status).toBe("passed");

    writeFileSync(
      source,
      `type CardProps = { title: string };\nconst fallback = "Untitled";\nexport const Card = (props: CardProps) => <div>{props.title || fallback}</div>;\n`,
    );
    const failed = runConventionChecks(root, discoverComponents(root));
    expect(failed.status).toBe("failed");
    expect(failed.diagnostics[0]?.message).toContain(
      "CardProps must appear immediately before Card",
    );
  });

  test("does not infer a React ordering rule when a matching props type is not consumed", () => {
    const root = reactRepository();
    enforce(root, "REACT-005", "react-props-adjacency");
    writeFileSync(
      join(root, "src", "Card.tsx"),
      `type CardProps = { title: string };\nconst helper = 1;\nexport function Card() { return <div>{helper}</div>; }\n`,
    );

    expect(runConventionChecks(root, discoverComponents(root)).status).toBe("passed");
  });

  test("orders C# members by kind and then accessibility", () => {
    const root = dotnetRepository();
    const source = join(root, "Service.cs");
    enforce(root, "CSHARP-001", "csharp-member-order");

    writeFileSync(
      source,
      `public class Service\n{\n    private readonly int[] _values = new[] { 1, 2 };\n\n    public Service() { }\n\n    public int Count { get; } = 2;\n    private int Hidden => 1;\n\n    public void Run() { }\n    internal void RunInternal() { }\n    protected void RunProtected() { }\n    private void Stop() { }\n}\n`,
    );
    expect(runConventionChecks(root, discoverComponents(root)).status).toBe("passed");

    writeFileSync(
      source,
      `public class Service\n{\n    private void Hidden() { }\n    public void Visible() { }\n}\n`,
    );
    let failed = runConventionChecks(root, discoverComponents(root));
    expect(failed.status).toBe("failed");
    expect(failed.diagnostics[0]?.message).toContain(
      "method is out of canonical kind/access order",
    );

    writeFileSync(
      source,
      `public class Service\n{\n    public void Run() { }\n    public int Count { get; }\n}\n`,
    );
    failed = runConventionChecks(root, discoverComponents(root));
    expect(failed.status).toBe("failed");
    expect(failed.diagnostics[0]?.message).toContain(
      "property is out of canonical kind/access order",
    );
  });

  test("checks nested C# types but skips generated and conditionally compiled source", () => {
    const root = dotnetRepository();
    enforce(root, "CSHARP-001", "csharp-member-order");
    writeFileSync(
      join(root, "Nested.cs"),
      `public class Outer\n{\n    private class Inner\n    {\n        private void Hidden() { }\n        public void Visible() { }\n    }\n}\n`,
    );
    expect(runConventionChecks(root, discoverComponents(root)).status).toBe("failed");

    writeFileSync(join(root, "Nested.cs"), "// <auto-generated>\npublic class Generated { }\n");
    writeFileSync(
      join(root, "Conditional.cs"),
      `#if DEBUG\npublic class Conditional { private void B() { } public void A() { } }\n#endif\n`,
    );
    expect(runConventionChecks(root, discoverComponents(root)).status).toBe("passed");
  });
});
