import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { renderSourceDependencies, sourceDependencies } from "../src/source-deps.ts";

function repository(): string {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-source-deps-"));
  writeFileSync(
    join(root, ".coding-tooling.source-deps.json"),
    JSON.stringify({
      schemaVersion: 1,
      cargo: {
        patches: [
          {
            package: "z-package",
            git: "https://github.com/example/source.git",
            rev: "2222222222222222222222222222222222222222",
          },
          {
            package: "a-package",
            git: "https://github.com/example/source.git",
            rev: "1111111111111111111111111111111111111111",
          },
        ],
      },
    }),
  );
  return root;
}

describe("source dependency mode", () => {
  test("renders deterministic exact-revision Cargo patches", () => {
    const root = repository();
    const rendered = renderSourceDependencies(root);
    expect(rendered.packages).toEqual(["a-package", "z-package"]);
    expect(rendered.content).toContain("[patch.crates-io]");
    expect(rendered.content.indexOf('"a-package"')).toBeLessThan(
      rendered.content.indexOf('"z-package"'),
    );
    expect(rendered.content).toContain('rev = "1111111111111111111111111111111111111111"');
  });

  test("activates and deactivates only the managed Cargo config", () => {
    const root = repository();
    const activated = sourceDependencies(root, "activate");
    expect(activated.status).toBe("passed");
    const cargoConfig = join(root, ".cargo", "config.toml");
    expect(existsSync(cargoConfig)).toBe(true);
    expect(
      readFileSync(cargoConfig, "utf8").startsWith("# Generated by coding-tooling source-deps."),
    ).toBe(true);

    const deactivated = sourceDependencies(root, "deactivate");
    expect(deactivated.status).toBe("passed");
    expect(existsSync(cargoConfig)).toBe(false);
  });
});
