import { expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { type ResultEnvelope, type ResultOperation } from "../src/model.ts";
import { runSourceAwarePipeline } from "../src/source-aware-pipeline.ts";

function envelope(
  operation: ResultOperation,
  status: ResultEnvelope<Record<string, unknown>>["status"] = "passed",
  data: Record<string, unknown> = {},
): ResultEnvelope<Record<string, unknown>> {
  return {
    schemaVersion: 1,
    operation,
    status,
    durationMs: 1,
    data,
    diagnostics: status === "passed" ? [] : [{ code: `${operation}-failed`, message: "failed" }],
  };
}

function sourceRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-source-pr-"));
  mkdirSync(join(root, "apps", "desktop"), { recursive: true });
  writeFileSync(join(root, "apps", "desktop", "Cargo.lock"), "distribution-lock\n");
  writeFileSync(
    join(root, ".coding-tooling.source-deps.json"),
    `${JSON.stringify(
      {
        schemaVersion: 2,
        cargo: {
          localOnly: true,
          patches: [],
        },
      },
      null,
      2,
    )}\n`,
  );
  return root;
}

test("keeps ordinary PR pipelines unchanged without local-only source mode", () => {
  const root = mkdtempSync(join(tmpdir(), "coding-tooling-plain-pr-"));
  try {
    let calls = 0;
    const execution = runSourceAwarePipeline(root, "full", {
      runPipeline: () => {
        calls += 1;
        return envelope("run");
      },
    });

    expect(execution.pipeline.status).toBe("passed");
    expect(execution.sourceDevelopment).toBe(false);
    expect(calls).toBe(1);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("activates exact sources, verifies the source fingerprint, and restores distribution state", () => {
  const root = sourceRoot();
  const cargoLock = join(root, "apps", "desktop", "Cargo.lock");
  const cargoConfig = join(root, ".cargo", "config.toml");
  try {
    let pipelineCalls = 0;
    let environmentCalls = 0;
    const execution = runSourceAwarePipeline(root, "full", {
      sourceDependencies: (_root, action) => {
        expect(action).toBe("activate");
        mkdirSync(join(root, ".cargo"), { recursive: true });
        writeFileSync(cargoConfig, "# Generated by coding-tooling source-deps. Do not edit.\n");
        writeFileSync(cargoLock, "source-resolution-lock\n");
        return envelope("source-deps", "passed", {
          action,
          active: true,
          resolution: "local-only",
        });
      },
      verifyEnvironment: (_root, profile) => {
        environmentCalls += 1;
        expect(profile).toBe("source-development");
        return envelope("environment", "passed", {
          expectedFingerprint: "env-v1:fixture",
          verifiedFingerprint: "env-v1:fixture",
        });
      },
      runPipeline: () => {
        pipelineCalls += 1;
        writeFileSync(cargoLock, "pipeline-mutated-lock\n");
        return envelope("run");
      },
    });

    expect(execution.pipeline.status).toBe("passed");
    expect(execution.sourceDevelopment).toBe(true);
    expect(execution.environment?.data.verifiedFingerprint).toBe("env-v1:fixture");
    expect(environmentCalls).toBe(1);
    expect(pipelineCalls).toBe(1);
    expect(readFileSync(cargoLock, "utf8")).toBe("distribution-lock\n");
    expect(() => readFileSync(cargoConfig, "utf8")).toThrow();
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("fails closed before the pipeline when source activation fails", () => {
  const root = sourceRoot();
  try {
    let pipelineCalls = 0;
    let environmentCalls = 0;
    const execution = runSourceAwarePipeline(root, "full", {
      sourceDependencies: () => envelope("source-deps", "failed"),
      verifyEnvironment: () => {
        environmentCalls += 1;
        return envelope("environment");
      },
      runPipeline: () => {
        pipelineCalls += 1;
        return envelope("run");
      },
    });

    expect(execution.pipeline.status).toBe("failed");
    expect(execution.pipeline.data.phase).toBe("source-activation");
    expect(environmentCalls).toBe(0);
    expect(pipelineCalls).toBe(0);
    expect(readFileSync(join(root, "apps", "desktop", "Cargo.lock"), "utf8")).toBe(
      "distribution-lock\n",
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("fails closed before repository checks when the source-development environment is not certified", () => {
  const root = sourceRoot();
  try {
    let pipelineCalls = 0;
    const execution = runSourceAwarePipeline(root, "full", {
      sourceDependencies: () => envelope("source-deps"),
      verifyEnvironment: () =>
        envelope("environment", "failed", {
          expectedFingerprint: "env-v1:expected",
          verifiedFingerprint: null,
        }),
      runPipeline: () => {
        pipelineCalls += 1;
        return envelope("run");
      },
    });

    expect(execution.pipeline.status).toBe("failed");
    expect(execution.pipeline.data.phase).toBe("environment-verification");
    expect(pipelineCalls).toBe(0);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
