import { readFileSync, statSync } from "node:fs";
import { extname, join, relative } from "node:path";

import type { Component } from "./model.ts";
import { walkFiles } from "./shared.ts";

type Token = {
  text: string;
  line: number;
};

function componentRoot(root: string, component: Component): string {
  return component.path === "." ? root : join(root, component.path);
}

function tokenize(source: string): Token[] {
  const tokens: Token[] = [];
  let index = 0;
  let line = 1;

  const advance = (count = 1): void => {
    for (let offset = 0; offset < count; offset += 1) {
      if (source[index + offset] === "\n") line += 1;
    }
    index += count;
  };

  const skipQuoted = (quote: string, verbatim = false): void => {
    advance();
    while (index < source.length) {
      const char = source[index]!;
      if (!verbatim && char === "\\") {
        advance(Math.min(2, source.length - index));
        continue;
      }
      if (char === quote) {
        if (verbatim && source[index + 1] === quote) {
          advance(2);
          continue;
        }
        advance();
        return;
      }
      advance();
    }
  };

  const skipRawString = (quotes: number): void => {
    advance(quotes);
    const terminator = '"'.repeat(quotes);
    while (index < source.length) {
      if (source.startsWith(terminator, index)) {
        advance(quotes);
        return;
      }
      advance();
    }
  };

  while (index < source.length) {
    const char = source[index]!;
    const next = source[index + 1];
    if (/\s/.test(char)) {
      advance();
      continue;
    }
    if (char === "/" && next === "/") {
      while (index < source.length && source[index] !== "\n") advance();
      continue;
    }
    if (char === "/" && next === "*") {
      advance(2);
      while (index < source.length && !(source[index] === "*" && source[index + 1] === "/")) {
        advance();
      }
      if (index < source.length) advance(2);
      continue;
    }
    if (char === "#") {
      while (index < source.length && source[index] !== "\n") advance();
      continue;
    }
    if (char === "'") {
      skipQuoted("'");
      continue;
    }

    const prefixStart = index;
    let prefixEnd = index;
    while (source[prefixEnd] === "$" || source[prefixEnd] === "@") prefixEnd += 1;
    if (source[prefixEnd] === '"') {
      const quoteCount = source.slice(prefixEnd).match(/^"+/)?.[0].length ?? 1;
      const verbatim = source.slice(prefixStart, prefixEnd).includes("@");
      advance(prefixEnd - prefixStart);
      if (quoteCount >= 3) skipRawString(quoteCount);
      else skipQuoted('"', verbatim);
      continue;
    }
    if (char === '"') {
      const quoteCount = source.slice(index).match(/^"+/)?.[0].length ?? 1;
      if (quoteCount >= 3) skipRawString(quoteCount);
      else skipQuoted('"');
      continue;
    }

    if (char === "@" && /[A-Za-z_]/.test(next ?? "")) {
      const start = index;
      const tokenLine = line;
      advance(2);
      while (index < source.length && /[A-Za-z0-9_]/.test(source[index]!)) advance();
      tokens.push({ text: source.slice(start, index), line: tokenLine });
      continue;
    }
    if (/[A-Za-z_]/.test(char)) {
      const start = index;
      const tokenLine = line;
      advance();
      while (index < source.length && /[A-Za-z0-9_]/.test(source[index]!)) advance();
      tokens.push({ text: source.slice(start, index), line: tokenLine });
      continue;
    }

    const compound = ["=>", "==", "!=", "<=", ">=", "??=", "&&", "||"].find((value) =>
      source.startsWith(value, index),
    );
    if (compound) {
      tokens.push({ text: compound, line });
      advance(compound.length);
      continue;
    }

    tokens.push({ text: char, line });
    advance();
  }

  return tokens;
}

function matching(tokens: Token[], open: string, close: string): Map<number, number> {
  const stack: number[] = [];
  const matches = new Map<number, number>();
  for (const [index, token] of tokens.entries()) {
    if (token.text === open) stack.push(index);
    else if (token.text === close) {
      const start = stack.pop();
      if (start !== undefined) {
        matches.set(start, index);
        matches.set(index, start);
      }
    }
  }
  return matches;
}

function conditionalBodyStart(
  tokens: Token[],
  keywordIndex: number,
  parens: Map<number, number>,
): number | undefined {
  const open = keywordIndex + 1;
  if (tokens[open]?.text !== "(") return undefined;
  const close = parens.get(open);
  return close === undefined ? undefined : close + 1;
}

function csharpExplicitControlFlowFailuresForSource(
  source: string,
  relativePath: string,
): string[] {
  if (/^\s*#(?:if|elif|else|endif)\b/m.test(source)) return [];
  if (/^\s*\/\/\s*<auto-generated[>\s]/im.test(source)) return [];

  const failures: string[] = [];
  const tokens = tokenize(source);
  const parens = matching(tokens, "(", ")");
  const braces = matching(tokens, "{", "}");
  const doWhile = new Set<number>();

  for (let index = 0; index < tokens.length; index += 1) {
    if (tokens[index]!.text !== "do") continue;
    const body = index + 1;
    if (tokens[body]?.text !== "{") {
      failures.push(`${relativePath}:${tokens[index]!.line}: do body must use braces`);
      continue;
    }
    const close = braces.get(body);
    if (close !== undefined && tokens[close + 1]?.text === "while") {
      doWhile.add(close + 1);
    }
  }

  const conditionalKeywords = new Set(["if", "for", "foreach", "while", "lock", "fixed"]);
  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index]!;
    if (conditionalKeywords.has(token.text)) {
      if (token.text === "while" && doWhile.has(index)) continue;
      const body = conditionalBodyStart(tokens, index, parens);
      if (body !== undefined && tokens[body]?.text !== "{") {
        failures.push(`${relativePath}:${token.line}: ${token.text} body must use braces`);
      }
      continue;
    }

    if (token.text === "using") {
      if (tokens[index + 1]?.text !== "(") continue;
      const body = conditionalBodyStart(tokens, index, parens);
      if (body !== undefined && tokens[body]?.text !== "{") {
        failures.push(`${relativePath}:${token.line}: using statement body must use braces`);
      }
      continue;
    }

    if (token.text === "else") {
      const next = tokens[index + 1]?.text;
      if (next !== "{" && next !== "if") {
        failures.push(`${relativePath}:${token.line}: else body must use braces`);
      }
    }
  }

  return failures;
}

export function csharpExplicitControlFlowFailures(root: string, components: Component[]): string[] {
  const failures: string[] = [];
  const roots = new Set(
    components
      .filter((component) => component.kind === "dotnet")
      .map((component) => componentRoot(root, component)),
  );
  for (const dotnetRoot of roots) {
    for (const file of walkFiles(dotnetRoot, 12).filter((candidate) => {
      const normalized = candidate.replaceAll("\\", "/");
      return extname(candidate) === ".cs" && !/(?:\.g|\.generated)\.cs$/i.test(normalized);
    })) {
      try {
        if (statSync(file).size > 1_000_000) continue;
        const relativePath = relative(root, file).replaceAll("\\", "/");
        failures.push(
          ...csharpExplicitControlFlowFailuresForSource(readFileSync(file, "utf8"), relativePath),
        );
      } catch {
        // The C# compiler remains authoritative for invalid or unreadable source.
      }
    }
  }
  return failures;
}
