import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { repositoryEnvironmentConformance } from "./environment-conformance.ts";
import {
  expectedEnvironmentFingerprint,
  type EnvironmentFingerprintProfile,
} from "./environment-fingerprint.ts";
import type { Diagnostic, ResultEnvelope, ResultStatus } from "./model.ts";
import { renderSourceDependencies } from "./source-deps.ts";

const generatedSourceHeader = "# Generated by coding-tooling source-deps. Do not edit.\n";

type ObservationStatus = "passed" | "failed" | "unavailable";

type NativeObservation = {
  package: string;
  status: ObservationStatus;
};

type SourceObservation = {
  profile: EnvironmentFingerprintProfile;
  active: boolean;
  status: ObservationStatus;
  detail?: string;
};

function resultStatus(statuses: ObservationStatus[]): ResultStatus {
  if (statuses.includes("failed")) return "failed";
  if (statuses.includes("unavailable")) return "unavailable";
  return "passed";
}

function expectedAptPackages(expected: ResultEnvelope<Record<string, unknown>>): string[] {
  const layers = expected.data.layers;
  if (!layers || typeof layers !== "object") return [];
  const native = (layers as Record<string, unknown>).native;
  if (!native || typeof native !== "object") return [];
  const inputs = (native as Record<string, unknown>).inputs;
  if (!inputs || typeof inputs !== "object") return [];
  const apt = (inputs as Record<string, unknown>).apt;
  return Array.isArray(apt) ? apt.filter((value): value is string => typeof value === "string") : [];
}

function nativeObservations(root: string, packages: string[]): {
  observations: NativeObservation[];
  diagnostics: Diagnostic[];
} {
  if (packages.length === 0) return { observations: [], diagnostics: [] };
  const probe = spawnSync("dpkg-query", ["--version"], {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "ignore", "ignore"],
  });
  if (probe.status !== 0) {
    return {
      observations: packages.map((packageName) => ({ package: packageName, status: "unavailable" })),
      diagnostics: [
        {
          code: "environment-native-verifier-unavailable",
          message:
            "Native apt requirements are declared but dpkg-query is unavailable; this backend cannot verify them yet",
          path: ".repository-environment.toml",
        },
      ],
    };
  }

  const observations: NativeObservation[] = [];
  const diagnostics: Diagnostic[] = [];
  for (const packageName of packages) {
    const result = spawnSync("dpkg-query", ["-W", "-f=${Status}", packageName], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    const installed =
      result.status === 0 &&
      typeof result.stdout === "string" &&
      result.stdout.trim() === "install ok installed";
    observations.push({ package: packageName, status: installed ? "passed" : "failed" });
    if (!installed) {
      diagnostics.push({
        code: "environment-native-requirement-missing",
        message: `Native requirement ${packageName} is declared but not installed`,
        path: ".repository-environment.toml",
      });
    }
  }
  return { observations, diagnostics };
}

function sourceObservation(
  root: string,
  profile: EnvironmentFingerprintProfile,
): { observation: SourceObservation; diagnostics: Diagnostic[] } {
  const cargoConfigPath = join(root, ".cargo", "config.toml");
  const existing = existsSync(cargoConfigPath) ? readFileSync(cargoConfigPath, "utf8") : null;
  const managed = existing?.startsWith(generatedSourceHeader) ?? false;

  if (profile === "default") {
    return managed
      ? {
          observation: { profile, active: true, status: "failed" },
          diagnostics: [
            {
              code: "environment-source-profile-mismatch",
              message: "Default environment fingerprint requires registry mode, but managed source mode is active",
              path: ".cargo/config.toml",
            },
          ],
        }
      : { observation: { profile, active: false, status: "passed" }, diagnostics: [] };
  }

  try {
    const rendered = renderSourceDependencies(root);
    if (!managed || existing !== rendered.content) {
      return {
        observation: {
          profile,
          active: managed,
          status: "failed",
          detail: managed ? "managed source config is stale" : "managed source config is inactive",
        },
        diagnostics: [
          {
            code: "environment-source-profile-mismatch",
            message: managed
              ? "Source-development environment has a stale managed Cargo source configuration"
              : "Source-development environment requires the managed Cargo source configuration to be active",
            path: ".cargo/config.toml",
          },
        ],
      };
    }
    return {
      observation: { profile, active: true, status: "passed" },
      diagnostics: [],
    };
  } catch (error) {
    return {
      observation: {
        profile,
        active: managed,
        status: "failed",
        detail: error instanceof Error ? error.message : String(error),
      },
      diagnostics: [
        {
          code: "environment-source-profile-mismatch",
          message: error instanceof Error ? error.message : String(error),
          path: ".coding-tooling.source-deps.json",
        },
      ],
    };
  }
}

export function verifyEnvironmentFingerprint(
  root: string,
  profile: EnvironmentFingerprintProfile = "default",
): ResultEnvelope<Record<string, unknown>> {
  const started = performance.now();
  const expected = expectedEnvironmentFingerprint(root, profile);
  if (expected.status !== "passed" || typeof expected.data.fingerprint !== "string") {
    return {
      schemaVersion: 1,
      operation: "environment",
      status: expected.status === "error" ? "error" : "failed",
      durationMs: Math.round(performance.now() - started),
      data: {
        action: "verify",
        fingerprintVersion: "environment-fingerprint-v1",
        profile,
        expectedFingerprint: expected.data.fingerprint ?? null,
        verifiedFingerprint: null,
        expected: expected.data,
      },
      diagnostics: expected.diagnostics,
    };
  }

  const environment = repositoryEnvironmentConformance(root);
  const blockingEnvironmentFindings = environment.findings.filter(
    (finding) => finding.severity === "error",
  );
  const native = nativeObservations(root, expectedAptPackages(expected));
  const source = sourceObservation(root, profile);
  const diagnostics: Diagnostic[] = [
    ...blockingEnvironmentFindings.map((finding) => ({
      code: finding.code,
      message: finding.message,
      path: finding.path,
    })),
    ...native.diagnostics,
    ...source.diagnostics,
  ];

  const environmentStatuses = blockingEnvironmentFindings.map((finding) => finding.status);
  const status = resultStatus([
    ...environmentStatuses,
    ...native.observations.map((observation) => observation.status),
    source.observation.status,
  ]);

  return {
    schemaVersion: 1,
    operation: "environment",
    status,
    durationMs: Math.round(performance.now() - started),
    data: {
      action: "verify",
      fingerprintVersion: "environment-fingerprint-v1",
      profile,
      expectedFingerprint: expected.data.fingerprint,
      verifiedFingerprint: status === "passed" ? expected.data.fingerprint : null,
      layers: expected.data.layers,
      observations: {
        environment: environment.data,
        native: native.observations,
        sources: source.observation,
      },
    },
    diagnostics,
  };
}
