import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";

import {
  activateJavaScriptSourceDependencies,
  deactivateJavaScriptSourceDependencies,
  type JavaScriptSourceConfig,
  parseJavaScriptSourceConfig,
  smokeJavaScriptSourceDependencies,
  statusJavaScriptSourceDependencies,
} from "./javascript-source-deps.ts";
import type { ResultEnvelope } from "./model.ts";
import { reconcileTextFile, reconciliationChanged } from "./reconciliation.ts";

const generatedHeader = "# Generated by coding-tooling source-deps. Do not edit.\n";
export const defaultSourceDependencyConfigPath = ".coding-tooling.source-deps.json";
const defaultCargoConfigPath = ".cargo/config.toml";

export type CargoSourcePatch = {
  package: string;
  git: string;
  rev: string;
  localPath?: string;
};

export type CargoSourceRepository = {
  git: string;
  rev: string;
  localPath?: string;
  packages: Array<{
    package: string;
    path?: string;
  }>;
};

export type SourceRepository = {
  ecosystem: "cargo" | "javascript";
  git: string;
  rev: string;
  localPath?: string;
  localOnly: boolean;
  packages: Array<{
    package: string;
    path?: string;
  }>;
};

type RawSourceDependencyConfig = {
  schemaVersion?: unknown;
  cargo?: {
    configPath?: unknown;
    localOnly?: unknown;
    patches?: unknown;
    repositories?: unknown;
  };
  javascript?: unknown;
};

export type LoadedSourceDependencyConfig = {
  path: string;
  schemaVersion: 1 | 2 | 3 | 4;
  cargoConfigPath: string;
  localOnly: boolean;
  patches: CargoSourcePatch[];
  repositories: CargoSourceRepository[];
  javascript: JavaScriptSourceConfig | null;
  sourceRepositories: SourceRepository[];
};

type SourceDependencyAction = "activate" | "status" | "smoke" | "deactivate";

function exactRevision(value: string): boolean {
  return /^[0-9a-f]{40}$/i.test(value);
}

function sourceRepositoryKey(git: string, rev: string): string {
  return `${git}\n${rev.toLowerCase()}`;
}

function requireString(value: unknown, message: string): string {
  if (typeof value !== "string" || !value.trim()) throw new Error(message);
  return value;
}

function normalizeLegacyRepositories(patches: CargoSourcePatch[]): CargoSourceRepository[] {
  const grouped = new Map<string, CargoSourceRepository>();
  for (const patch of patches) {
    const key = sourceRepositoryKey(patch.git, patch.rev);
    const repository = grouped.get(key) ?? {
      git: patch.git,
      rev: patch.rev,
      packages: [],
    };
    repository.packages.push({ package: patch.package });
    grouped.set(key, repository);
  }
  return [...grouped.values()]
    .map((repository) => ({
      ...repository,
      packages: repository.packages.sort((left, right) =>
        left.package.localeCompare(right.package),
      ),
    }))
    .sort((left, right) => left.git.localeCompare(right.git) || left.rev.localeCompare(right.rev));
}

function sourceRepositories(
  cargo: CargoSourceRepository[],
  cargoLocalOnly: boolean,
  javascript: JavaScriptSourceConfig | null,
): SourceRepository[] {
  const repositories: SourceRepository[] = cargo.map((repository) => ({
    ecosystem: "cargo",
    git: repository.git,
    rev: repository.rev,
    ...(repository.localPath ? { localPath: repository.localPath } : {}),
    localOnly: cargoLocalOnly,
    packages: repository.packages,
  }));
  for (const repository of javascript?.repositories ?? []) {
    repositories.push({
      ecosystem: "javascript",
      git: repository.git,
      rev: repository.rev,
      localPath: repository.localPath,
      localOnly: true,
      packages: repository.packages,
    });
  }
  return repositories.sort(
    (left, right) =>
      left.git.localeCompare(right.git) || left.ecosystem.localeCompare(right.ecosystem),
  );
}

export function readSourceDependencyConfig(
  root: string,
  configPath?: string,
): LoadedSourceDependencyConfig {
  const path = resolve(root, configPath ?? defaultSourceDependencyConfigPath);
  const parsed = JSON.parse(readFileSync(path, "utf8")) as RawSourceDependencyConfig;
  if (
    parsed.schemaVersion !== 1 &&
    parsed.schemaVersion !== 2 &&
    parsed.schemaVersion !== 3 &&
    parsed.schemaVersion !== 4
  ) {
    throw new Error(`Unsupported source dependency schema: ${path}`);
  }
  if (!parsed.cargo || typeof parsed.cargo !== "object") {
    throw new Error(`Invalid source dependency config: ${path}`);
  }
  if (parsed.schemaVersion !== 4 && parsed.javascript !== undefined) {
    throw new Error(`JavaScript source dependencies require schemaVersion 4: ${path}`);
  }

  const javascript =
    parsed.schemaVersion === 4 ? parseJavaScriptSourceConfig(parsed.javascript, path) : null;
  const localOnly = parsed.cargo.localOnly === true;
  if (localOnly && parsed.schemaVersion === 1) {
    throw new Error(
      `Local-only source dependency config requires schemaVersion 2 or newer so older tooling cannot silently fall back to remote Git: ${path}`,
    );
  }
  const configuredCargoPath =
    parsed.cargo.configPath === undefined
      ? defaultCargoConfigPath
      : requireString(parsed.cargo.configPath, `cargo.configPath must be a string: ${path}`);

  const seen = new Set<string>();
  if (parsed.schemaVersion === 1 || parsed.schemaVersion === 2) {
    if (!Array.isArray(parsed.cargo.patches)) {
      throw new Error(
        `Schema ${parsed.schemaVersion} source dependency config requires cargo.patches: ${path}`,
      );
    }
    const patches: CargoSourcePatch[] = parsed.cargo.patches.map((candidate, index) => {
      if (!candidate || typeof candidate !== "object") {
        throw new Error(`Invalid Cargo source patch at index ${index}: ${path}`);
      }
      const patch = candidate as Record<string, unknown>;
      const packageName = requireString(
        patch.package,
        `Every Cargo source patch requires package, git, and rev: ${path}`,
      );
      const git = requireString(
        patch.git,
        `Every Cargo source patch requires package, git, and rev: ${path}`,
      );
      const rev = requireString(
        patch.rev,
        `Every Cargo source patch requires package, git, and rev: ${path}`,
      );
      const localPath =
        patch.localPath === undefined
          ? undefined
          : requireString(
              patch.localPath,
              `localPath must be a string for ${packageName}: ${path}`,
            );
      if (localOnly && !localPath) {
        throw new Error(`Local-only source patch ${packageName} requires localPath: ${path}`);
      }
      if (seen.has(packageName)) throw new Error(`Duplicate Cargo source patch: ${packageName}`);
      seen.add(packageName);
      return { package: packageName, git, rev, ...(localPath ? { localPath } : {}) };
    });
    const repositories = normalizeLegacyRepositories(patches);
    return {
      path,
      schemaVersion: parsed.schemaVersion,
      cargoConfigPath: resolve(root, configuredCargoPath),
      localOnly,
      patches,
      repositories,
      javascript,
      sourceRepositories: sourceRepositories(repositories, localOnly, javascript),
    };
  }

  if (!Array.isArray(parsed.cargo.repositories)) {
    throw new Error(
      `Schema ${parsed.schemaVersion} source dependency config requires cargo.repositories: ${path}`,
    );
  }
  const seenRepositories = new Set<string>();
  const repositories: CargoSourceRepository[] = parsed.cargo.repositories.map(
    (candidate, index) => {
      if (!candidate || typeof candidate !== "object") {
        throw new Error(`Invalid Cargo source repository at index ${index}: ${path}`);
      }
      const repository = candidate as Record<string, unknown>;
      const git = requireString(
        repository.git,
        `Every source repository requires git and rev: ${path}`,
      );
      const rev = requireString(
        repository.rev,
        `Every source repository requires git and rev: ${path}`,
      );
      if (!exactRevision(rev)) {
        throw new Error(
          `Source repository ${git} requires an exact 40-character revision: ${path}`,
        );
      }
      const repositoryKey = git.replace(/\.git$/i, "").toLowerCase();
      if (seenRepositories.has(repositoryKey)) {
        throw new Error(
          `Schema ${parsed.schemaVersion} declares Cargo source repository more than once: ${git}`,
        );
      }
      seenRepositories.add(repositoryKey);
      const localPath =
        repository.localPath === undefined
          ? undefined
          : requireString(repository.localPath, `localPath must be a string for ${git}: ${path}`);
      if (localOnly && !localPath) {
        throw new Error(`Local-only source repository ${git} requires localPath: ${path}`);
      }
      if (!Array.isArray(repository.packages) || repository.packages.length === 0) {
        throw new Error(`Source repository ${git} must declare at least one package: ${path}`);
      }
      const packages = repository.packages.map((packageCandidate, packageIndex) => {
        if (!packageCandidate || typeof packageCandidate !== "object") {
          throw new Error(`Invalid package at ${git} index ${packageIndex}: ${path}`);
        }
        const packageRecord = packageCandidate as Record<string, unknown>;
        const packageName = requireString(
          packageRecord.package,
          `Every schema ${parsed.schemaVersion} Cargo package requires package: ${path}`,
        );
        const packagePath =
          packageRecord.path === undefined
            ? undefined
            : requireString(
                packageRecord.path,
                `Package path must be a string for ${packageName}: ${path}`,
              );
        if (seen.has(packageName)) throw new Error(`Duplicate Cargo source patch: ${packageName}`);
        seen.add(packageName);
        return { package: packageName, ...(packagePath ? { path: packagePath } : {}) };
      });
      packages.sort((left, right) => left.package.localeCompare(right.package));
      return { git, rev: rev.toLowerCase(), ...(localPath ? { localPath } : {}), packages };
    },
  );
  repositories.sort((left, right) => left.git.localeCompare(right.git));

  const patches = repositories.flatMap((repository) =>
    repository.packages.map((packageEntry) => ({
      package: packageEntry.package,
      git: repository.git,
      rev: repository.rev,
      ...(repository.localPath
        ? { localPath: join(repository.localPath, packageEntry.path ?? ".") }
        : {}),
    })),
  );

  return {
    path,
    schemaVersion: parsed.schemaVersion,
    cargoConfigPath: resolve(root, configuredCargoPath),
    localOnly,
    patches,
    repositories,
    javascript,
    sourceRepositories: sourceRepositories(repositories, localOnly, javascript),
  };
}

function escapeToml(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function localRevision(path: string): string {
  const result = spawnSync("git", ["-C", path, "rev-parse", "HEAD"], { encoding: "utf8" });
  if (result.status !== 0)
    throw new Error(`Cannot read Git revision for local source dependency: ${path}`);
  return result.stdout.trim();
}

function renderPatch(root: string, patch: CargoSourcePatch, localOnly: boolean): string {
  if (patch.localPath) {
    const localPath = resolve(root, patch.localPath);
    if (existsSync(localPath)) {
      const actualRevision = localRevision(localPath);
      if (actualRevision !== patch.rev) {
        throw new Error(
          `Local source dependency ${patch.package} is at ${actualRevision}, expected ${patch.rev}`,
        );
      }
      return `"${escapeToml(patch.package)}" = { path = "${escapeToml(localPath)}" }`;
    }
    if (localOnly) {
      throw new Error(
        `Local source dependency ${patch.package} is missing at ${localPath}; local-only source mode never fetches repository sources`,
      );
    }
  }
  return `"${escapeToml(patch.package)}" = { git = "${escapeToml(patch.git)}", rev = "${escapeToml(patch.rev)}" }`;
}

export function renderSourceDependencies(
  root: string,
  configPath?: string,
): {
  configPath: string;
  cargoConfigPath: string;
  content: string;
  packages: string[];
  localOnly: boolean;
  schemaVersion: 1 | 2 | 3 | 4;
} {
  const loaded = readSourceDependencyConfig(root, configPath);
  const patches = [...loaded.patches].sort((left, right) =>
    left.package.localeCompare(right.package),
  );
  const body = patches.map((patch) => renderPatch(root, patch, loaded.localOnly)).join("\n");
  return {
    configPath: loaded.path,
    cargoConfigPath: loaded.cargoConfigPath,
    content: `${generatedHeader}\n[patch.crates-io]\n${body}\n`,
    packages: patches.map((patch) => patch.package),
    localOnly: loaded.localOnly,
    schemaVersion: loaded.schemaVersion,
  };
}

function javascriptPackages(config: JavaScriptSourceConfig | null): string[] {
  return (config?.repositories ?? [])
    .flatMap((repository) => repository.packages.map((entry) => entry.package))
    .sort();
}

export function sourceDependencies(
  root: string,
  action: SourceDependencyAction,
  configPath?: string,
): ResultEnvelope<Record<string, unknown>> {
  const started = performance.now();
  try {
    const loaded = readSourceDependencyConfig(root, configPath);
    const existing = existsSync(loaded.cargoConfigPath)
      ? readFileSync(loaded.cargoConfigPath, "utf8")
      : undefined;
    const managed = existing?.startsWith(generatedHeader) ?? false;
    const cargoPackages = loaded.patches.map((patch) => patch.package).sort();
    const jsPackages = javascriptPackages(loaded.javascript);
    const packages = [...new Set([...cargoPackages, ...jsPackages])].sort();

    if (action === "deactivate") {
      if (existing !== undefined && !managed) {
        throw new Error(`Refusing to remove unmanaged Cargo config: ${loaded.cargoConfigPath}`);
      }
      const javascript = loaded.javascript
        ? deactivateJavaScriptSourceDependencies(root, loaded.javascript)
        : null;
      const reconciliation = managed ? "changed" : "unchanged";
      if (managed) rmSync(loaded.cargoConfigPath);
      return {
        schemaVersion: 1,
        operation: "source-deps",
        status: "passed",
        durationMs: Math.round(performance.now() - started),
        data: {
          action,
          active: false,
          changed: reconciliation === "changed",
          reconciliation,
          sourceSchemaVersion: loaded.schemaVersion,
          configPath: loaded.path,
          cargoConfigPath: loaded.cargoConfigPath,
          packages,
          cargoPackages,
          javascriptPackages: jsPackages,
          javascript,
          resolution: loaded.localOnly ? "local-only" : "local-or-git",
          javascriptResolution: loaded.javascript ? "local-only" : null,
        },
        diagnostics: [],
      };
    }

    if (action === "smoke") {
      if (!managed)
        throw new Error(`Source dependency mode is not active: ${loaded.cargoConfigPath}`);
      const javascript = loaded.javascript
        ? smokeJavaScriptSourceDependencies(root, loaded.javascript)
        : null;
      return {
        schemaVersion: 1,
        operation: "source-deps",
        status: "passed",
        durationMs: Math.round(performance.now() - started),
        data: {
          action,
          active: true,
          sourceSchemaVersion: loaded.schemaVersion,
          configPath: loaded.path,
          cargoConfigPath: loaded.cargoConfigPath,
          packages,
          cargoPackages,
          javascriptPackages: jsPackages,
          javascript,
        },
        diagnostics: [],
      };
    }

    const rendered = renderSourceDependencies(root, configPath);
    let reconciliation: "created" | "changed" | "unchanged" = "unchanged";
    let javascript: Record<string, unknown> | null = null;
    if (action === "activate") {
      if (existing !== undefined && !managed) {
        throw new Error(
          `Refusing to overwrite unmanaged Cargo config: ${rendered.cargoConfigPath}`,
        );
      }
      reconciliation = reconcileTextFile(rendered.cargoConfigPath, rendered.content);
      try {
        javascript = loaded.javascript
          ? activateJavaScriptSourceDependencies(root, loaded.javascript)
          : null;
      } catch (error) {
        if (existing === undefined) rmSync(rendered.cargoConfigPath, { force: true });
        else if (managed) reconcileTextFile(rendered.cargoConfigPath, existing);
        throw error;
      }
    } else {
      javascript = loaded.javascript
        ? statusJavaScriptSourceDependencies(root, loaded.javascript)
        : null;
    }
    const javascriptActive =
      !loaded.javascript || (javascript !== null && javascript.active === true);

    return {
      schemaVersion: 1,
      operation: "source-deps",
      status: "passed",
      durationMs: Math.round(performance.now() - started),
      data: {
        action,
        active: action === "activate" ? true : managed && javascriptActive,
        changed: action === "activate" ? reconciliationChanged(reconciliation) : false,
        reconciliation,
        sourceSchemaVersion: rendered.schemaVersion,
        configPath: rendered.configPath,
        cargoConfigPath: rendered.cargoConfigPath,
        packages,
        cargoPackages,
        javascriptPackages: jsPackages,
        javascript,
        resolution: rendered.localOnly ? "local-only" : "local-or-git",
        javascriptResolution: loaded.javascript ? "local-only" : null,
      },
      diagnostics: [],
    };
  } catch (error) {
    return {
      schemaVersion: 1,
      operation: "source-deps",
      status: "error",
      durationMs: Math.round(performance.now() - started),
      data: { action },
      diagnostics: [{ message: error instanceof Error ? error.message : String(error) }],
    };
  }
}
