import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import type { ResultEnvelope } from "./model.ts";

const generatedHeader = "# Generated by coding-tooling source-deps. Do not edit.\n";
const defaultConfigPath = ".coding-tooling.source-deps.json";
const defaultCargoConfigPath = ".cargo/config.toml";

type CargoSourcePatch = {
  package: string;
  git: string;
  rev: string;
  localPath?: string;
};

type SourceDependencyConfig = {
  schemaVersion: 1;
  cargo: {
    configPath?: string;
    patches: CargoSourcePatch[];
  };
};

type SourceDependencyAction = "activate" | "status" | "deactivate";

function escapeToml(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function loadConfig(
  root: string,
  configPath?: string,
): { path: string; config: SourceDependencyConfig } {
  const path = resolve(root, configPath ?? defaultConfigPath);
  const parsed = JSON.parse(readFileSync(path, "utf8")) as Partial<SourceDependencyConfig>;
  if (parsed.schemaVersion !== 1 || !parsed.cargo || !Array.isArray(parsed.cargo.patches)) {
    throw new Error(`Invalid source dependency config: ${path}`);
  }
  const seen = new Set<string>();
  for (const patch of parsed.cargo.patches) {
    if (!patch.package || !patch.git || !patch.rev) {
      throw new Error(`Every Cargo source patch requires package, git, and rev: ${path}`);
    }
    if (seen.has(patch.package)) throw new Error(`Duplicate Cargo source patch: ${patch.package}`);
    seen.add(patch.package);
  }
  return { path, config: parsed as SourceDependencyConfig };
}

function localRevision(path: string): string {
  const result = spawnSync("git", ["-C", path, "rev-parse", "HEAD"], { encoding: "utf8" });
  if (result.status !== 0)
    throw new Error(`Cannot read Git revision for local source dependency: ${path}`);
  return result.stdout.trim();
}

function renderPatch(root: string, patch: CargoSourcePatch): string {
  if (patch.localPath) {
    const localPath = resolve(root, patch.localPath);
    if (existsSync(localPath)) {
      const actualRevision = localRevision(localPath);
      if (actualRevision !== patch.rev) {
        throw new Error(
          `Local source dependency ${patch.package} is at ${actualRevision}, expected ${patch.rev}`,
        );
      }
      return `"${escapeToml(patch.package)}" = { path = "${escapeToml(localPath)}" }`;
    }
  }
  return `"${escapeToml(patch.package)}" = { git = "${escapeToml(patch.git)}", rev = "${escapeToml(patch.rev)}" }`;
}

export function renderSourceDependencies(
  root: string,
  configPath?: string,
): {
  configPath: string;
  cargoConfigPath: string;
  content: string;
  packages: string[];
} {
  const loaded = loadConfig(root, configPath);
  const patches = loaded.config.cargo.patches.toSorted((left, right) =>
    left.package.localeCompare(right.package),
  );
  const cargoConfigPath = resolve(root, loaded.config.cargo.configPath ?? defaultCargoConfigPath);
  const body = patches.map((patch) => renderPatch(root, patch)).join("\n");
  return {
    configPath: loaded.path,
    cargoConfigPath,
    content: `${generatedHeader}\n[patch.crates-io]\n${body}\n`,
    packages: patches.map((patch) => patch.package),
  };
}

export function sourceDependencies(
  root: string,
  action: SourceDependencyAction,
  configPath?: string,
): ResultEnvelope<Record<string, unknown>> {
  const started = performance.now();
  try {
    const loaded = loadConfig(root, configPath);
    const cargoConfigPath = resolve(root, loaded.config.cargo.configPath ?? defaultCargoConfigPath);
    const packages = loaded.config.cargo.patches.map((patch) => patch.package).toSorted();
    const existing = existsSync(cargoConfigPath)
      ? readFileSync(cargoConfigPath, "utf8")
      : undefined;
    const managed = existing?.startsWith(generatedHeader) ?? false;

    if (action === "deactivate") {
      if (existing !== undefined && !managed) {
        throw new Error(`Refusing to remove unmanaged Cargo config: ${cargoConfigPath}`);
      }
      if (managed) rmSync(cargoConfigPath);
      return {
        schemaVersion: 1,
        operation: "source-deps",
        status: "passed",
        durationMs: Math.round(performance.now() - started),
        data: { action, active: false, configPath: loaded.path, cargoConfigPath, packages },
        diagnostics: [],
      };
    }

    const rendered = renderSourceDependencies(root, configPath);
    if (action === "activate") {
      if (existing !== undefined && !managed) {
        throw new Error(
          `Refusing to overwrite unmanaged Cargo config: ${rendered.cargoConfigPath}`,
        );
      }
      mkdirSync(dirname(rendered.cargoConfigPath), { recursive: true });
      writeFileSync(rendered.cargoConfigPath, rendered.content);
    }

    return {
      schemaVersion: 1,
      operation: "source-deps",
      status: "passed",
      durationMs: Math.round(performance.now() - started),
      data: {
        action,
        active: action === "activate" ? true : managed,
        configPath: rendered.configPath,
        cargoConfigPath: rendered.cargoConfigPath,
        packages: rendered.packages,
      },
      diagnostics: [],
    };
  } catch (error) {
    return {
      schemaVersion: 1,
      operation: "source-deps",
      status: "error",
      durationMs: Math.round(performance.now() - started),
      data: { action },
      diagnostics: [{ message: error instanceof Error ? error.message : String(error) }],
    };
  }
}
